#!/usr/bin/env bash
# Clean step: remove files generated by this workflow. Keeps the skill, boards/ and every file
# the skill did not create. App SOURCES are kept unless --apps is given.
#
# Usage: clean.sh [--apps] [--yes] [workspace]
#   workspace     the apps folder new_app.sh writes to (default: $PSE84_WS)
#   (default)     build outputs only: <app>/build, proj_*/build, proj_*/libs, mtb_shared, .cache.
#                 App sources, tests, logs and .bench are kept (rebuild: build.sh <app> --getlibs)
#   --apps        ALSO delete whole apps created by new_app.sh (identified by <app>/pse84-app.env)
#                 and .bench - your source code goes too. Published apps (APP_PUBLISHED=1 in
#                 pse84-app.env) still lose only their build outputs.
#   --build-only  accepted for compatibility (= default)
#   --yes         actually delete. Without it, only lists what would be deleted (dry run).
# Never deleted: the skill, anything outside the workspace, folders without pse84-app.env.

. "$(dirname "$0")/env.sh"
YES=0; BUILD_ONLY=1; WS=""
for a in "$@"; do
  case "$a" in
    --yes) YES=1;; --build-only) BUILD_ONLY=1;; --apps) BUILD_ONLY=0;;
    --*) die "unknown option $a";;
    *) WS="$a";;
  esac
done
WS="${WS:-$PSE84_WS}"
if [ ! -d "$WS" ]; then echo "Nothing to clean (no workspace $WS)."; exit 0; fi
APPS="$(cd "$WS" && pwd)"
ROOT="$APPS"                                   # everything below must stay inside here
case "$APPS" in /|/c|/[a-z]|"$(cd "$HOME" && pwd)") die "refusing to clean $APPS (not an apps workspace)";; esac
for m in .claude skills boards; do
  [ -d "$APPS/$m" ] && die "refusing: $APPS contains $m/ - pass the apps folder, not the repo/project root"
done
marker=0   # any one of these marks a pse84 apps workspace
for m in "$APPS"/*/pse84-app.env "$APPS/.bench" "$APPS/mtb_shared"; do [ -e "$m" ] && marker=1; done
[ $marker = 1 ] || { echo "Nothing to clean in $APPS (no pse84 apps, .bench or mtb_shared)."; exit 0; }

targets=()
add() { [ -e "$1" ] && targets+=("$1"); }
if [ -d "$APPS" ]; then
  for d in "$APPS"/*/; do
    d="${d%/}"; [ -f "$d/pse84-app.env" ] || continue
    if [ $BUILD_ONLY = 1 ] || grep -q '^APP_PUBLISHED=1' "$d/pse84-app.env"; then
      add "$d/build"
      for p in "$d"/proj_*; do add "$p/build"; add "$p/libs"; done
    else
      add "$d"
    fi
  done
  add "$APPS/mtb_shared"
  add "$APPS/.cache"
  [ $BUILD_ONLY = 1 ] || add "$APPS/.bench"
fi

echo "Workspace: $APPS"
echo "Mode: $([ $BUILD_ONLY = 1 ] && echo 'build outputs only (app sources kept; --apps deletes apps too)' || echo 'WHOLE APPS (sources included) + libraries + .bench')"
if [ ${#targets[@]} -eq 0 ]; then echo "Nothing to clean."; exit 0; fi
for t in "${targets[@]}"; do
  case "$t" in "$ROOT"/*) ;; *) die "refusing: $t is outside $ROOT";; esac
  case "$SKILL_DIR" in "$t"|"$t"/*) die "refusing to delete $t (contains the skill)";; esac
  printf '  %s  (%s)\n' "${t#$ROOT/}" "$(du -sh "$t" 2>/dev/null | cut -f1)"
done
if [ $YES = 0 ]; then
  echo "DRY RUN - nothing deleted. Re-run with --yes to delete the items above."; need_user APPROVE "delete the items listed above (re-run clean.sh with --yes after the user agrees)"
  exit 0
fi
# Delete with retries: cloud-sync clients (Dropbox/OneDrive) and antivirus briefly lock files
left=()
for t in "${targets[@]}"; do
  for try in 1 2 3 4 5; do
    rm -rf -- "$t" 2>/dev/null
    [ -e "$t" ] || break
    sleep 2
  done
  if [ -e "$t" ]; then left+=("$t"); else echo "deleted ${t#$ROOT/}"; fi
done
[ -d "$APPS" ] && [ $BUILD_ONLY = 0 ] && rmdir "$APPS" 2>/dev/null && echo "deleted apps/ (empty)"
if [ ${#left[@]} -gt 0 ]; then
  echo "Still present (locked by another program):"
  for t in "${left[@]}"; do echo "  ${t#$ROOT/}"; done
  [ -n "$(path_synced "$APPS")" ] && echo "Hint: $(path_synced "$APPS") is syncing this folder - pause sync, close editors/terminals in apps/, then re-run clean.sh --yes"
  echo "CLEAN: INCOMPLETE"; exit 1
fi
echo "CLEAN: done ($APPS). The skill and files outside the workspace were not touched."
