/*******************************************************************************
* File Name : board.h
*
* Layer 1 - board adaptation for STM32N6 boards (STM32CubeN6 HAL, generated by
* STM32CubeMX). The ONLY place for GPIO ports/pins, HAL calls and BOARD_xxx
* #ifdefs. func/ and app_main.c use this API only (docs/board-api.md - the same
* API as the modus-pdl-edgitalk and cubemx2-hal2-stm32c562nucleo skills, so lib/func is shared
* unchanged).
*
* The board id reaches C as -DBOARD_<ID> (added to mx/FSBL/CMakeLists.txt by
* overlay.py); this file maps it to BOARD_NAME and the user I/O.
*******************************************************************************/
#ifndef BOARD_H
#define BOARD_H

#include <stdbool.h>
#include <stdint.h>

#if defined(BOARD_STM32N6570_DK)
    #define BOARD_NAME          "stm32n6570-dk"
#else
    #define BOARD_NAME          "generic-stm32n6"
#endif

/* Upper bounds for static tables in func/ */
#define BOARD_MAX_LEDS          (4U)
#define BOARD_MAX_BUTTONS       (4U)

/* System */
void     board_early_init(void);         /* before SystemClock_Config(): supply for the clock */
void     board_init(void);               /* user I/O + console; after the generated MX_..._Init() */
void     board_delay_ms(uint32_t ms);
uint32_t board_millis(void);             /* ms since reset (HAL tick)                  */
void     board_fatal(void);              /* stop execution on unrecoverable error      */

/* User LEDs, index 0..board_led_count()-1 (LED1 = index 0) */
uint32_t    board_led_count(void);
void        board_led_write(uint32_t idx, bool on);
bool        board_led_read(uint32_t idx);         /* read back the output register */
const char *board_led_name(uint32_t idx);         /* "LED1"                        */

/* User buttons, index 0..board_button_count()-1 (BTN1 = index 0) */
uint32_t    board_button_count(void);
bool        board_button_is_pressed(uint32_t idx);  /* raw, not debounced       */
const char *board_button_name(uint32_t idx);        /* "USER1"                  */
const char *board_button_pin(uint32_t idx);         /* e.g. "PC13"              */

/* Console UART (USART1, routed to the ST-LINK virtual COM port). printf() also works. */
bool     board_console_getc(char *c);    /* non-blocking; true if a byte was read */
void     board_console_flush(void);

#endif /* BOARD_H */
