#!/usr/bin/env bash
# Stage 7: remove files generated by this workflow. Keeps the skill, boards/ and every file the
# skill did not create. App SOURCES are kept unless --apps is given. RT-Thread Studio and its SDK
# packages (C:/RT-ThreadStudio) and the Studio workspace metadata (<apps>/.rtstudio) stay.
#
# Usage: clean.sh [--apps] [--yes] [workspace]
#   workspace  the apps folder new_app.sh writes to (default: $RTT_WS)
#   (default)  build outputs only: <app>/build, rtthread.elf/.hex/.map, app.hex (rebuild with
#              build.sh). Sources, tests, logs and .bench are kept
#   --apps     ALSO delete whole apps created by new_app.sh (identified by <app>/rtt-app.env),
#              .bench and the Studio workspace .rtstudio - your source code goes too. Published apps (APP_PUBLISHED=1 in
#              rtt-app.env) still lose only their build outputs.
#   --yes      actually delete. Without it, only lists what would be deleted (dry run).

. "$(dirname "$0")/env.sh"
YES=0; APPS_TOO=0; WS=""
for a in "$@"; do
  case "$a" in --yes) YES=1;; --apps) APPS_TOO=1;; --*) die "unknown option $a";; *) WS="$a";; esac
done
WS="${WS:-$RTT_WS}"
if [ ! -d "$WS" ]; then echo "Nothing to clean (no workspace $WS)."; exit 0; fi
APPS="$(cd "$WS" && pwd)"
case "$APPS" in /|/c|/[a-z]|"$(cd "$HOME" && pwd)") die "refusing to clean $APPS (not an apps workspace)";; esac
for m in .claude skills boards; do
  [ -d "$APPS/$m" ] && die "refusing: $APPS contains $m/ - pass the apps folder, not the repo/project root"
done

targets=()
add() { [ -e "$1" ] && targets+=("$1"); }
for d in "$APPS"/*/; do
  d="${d%/}"; [ -f "$d/rtt-app.env" ] || continue
  if [ $APPS_TOO = 1 ] && ! grep -q '^APP_PUBLISHED=1' "$d/rtt-app.env"; then add "$d"; continue; fi
  for o in build rtthread.elf rtthread.hex rtthread.map app.hex .sconsign.dblite; do add "$d/$o"; done
done
[ $APPS_TOO = 1 ] && { add "$APPS/.bench"; add "$APPS/.rtstudio"; }

echo "Workspace: $APPS"
echo "Mode: $([ $APPS_TOO = 1 ] && echo 'WHOLE APPS (sources included) + .bench + .rtstudio' || echo 'build outputs only (app sources kept; --apps deletes apps too)')"
if [ ${#targets[@]} -eq 0 ]; then echo "Nothing to clean."; exit 0; fi
for t in "${targets[@]}"; do
  case "$t" in "$APPS"/*) ;; *) die "refusing: $t is outside $APPS";; esac
  printf '  %s  (%s)\n' "${t#$APPS/}" "$(du -sh "$t" 2>/dev/null | cut -f1)"
done
if [ $YES = 0 ]; then echo "DRY RUN - nothing deleted. Re-run with --yes to delete the items above."; need_user APPROVE "delete the items listed above (re-run clean.sh with --yes after the user agrees)"; exit 0; fi
left=()
for t in "${targets[@]}"; do
  for try in 1 2 3 4 5; do rm -rf -- "$t" 2>/dev/null; [ -e "$t" ] || break; sleep 2; done
  if [ -e "$t" ]; then left+=("$t"); else echo "deleted ${t#$APPS/}"; fi
done
if [ ${#left[@]} -gt 0 ]; then
  echo "Still present (locked by another program - close serial monitors / pause cloud sync):"
  for t in "${left[@]}"; do echo "  ${t#$APPS/}"; done
  echo "CLEAN: INCOMPLETE"; exit 1
fi
echo "CLEAN: done ($APPS)"
