/*******************************************************************************
* File Name : board.h
*
* Layer 1 - board adaptation for STM32F4 boards (STM32CubeF4 HAL, generated by
* STM32CubeMX). The ONLY place for GPIO ports/pins, HAL/CMSIS calls and
* BOARD_xxx #ifdefs. func/ and app_main.c use this API only (docs/board-api.md -
* the same API as the other C skills, so lib/func is shared unchanged).
*
* The board id reaches C as -DBOARD_<ID> (added to mx/CMakeLists.txt by
* overlay.py); this file maps it to BOARD_NAME and the user I/O.
*******************************************************************************/
#ifndef BOARD_H
#define BOARD_H

#include <stdbool.h>
#include <stdint.h>

#if defined(BOARD_STM32F407G_DISC1)
    #define BOARD_NAME          "stm32f407g-disc1"
#else
    #define BOARD_NAME          "generic-stm32f4"
#endif

/* Upper bounds for static tables in func/ */
#define BOARD_MAX_LEDS          (4U)
#define BOARD_MAX_BUTTONS       (4U)

/* System */
void     board_init(void);               /* after the generated MX_..._Init(): console check */
void     board_delay_ms(uint32_t ms);
uint32_t board_millis(void);             /* ms since reset (HAL tick)                  */
void     board_fatal(void);              /* stop execution on unrecoverable error      */

/* User LEDs, index 0..board_led_count()-1 (LED1 = index 0) */
uint32_t    board_led_count(void);
void        board_led_write(uint32_t idx, bool on);
bool        board_led_read(uint32_t idx);         /* read back the output register */
const char *board_led_name(uint32_t idx);         /* silkscreen name, "LD3"        */

/* User buttons, index 0..board_button_count()-1 (BTN1 = index 0) */
uint32_t    board_button_count(void);
bool        board_button_is_pressed(uint32_t idx);  /* raw, not debounced       */
const char *board_button_name(uint32_t idx);        /* "B1"                     */
const char *board_button_pin(uint32_t idx);         /* e.g. "PA0"               */

/* Console: output only, SWO (ITM stimulus port 0) through the ST-LINK. printf() works.
 * There is no console input on this board (ST-LINK/V2 without virtual COM port). */
bool     board_console_getc(char *c);    /* always false: no input path            */
void     board_console_flush(void);

#endif /* BOARD_H */
