#!/usr/bin/env bash
# Stage 2b: create a PlatformIO + Arduino app for a board from a layered template. Needs no
# hardware and no network (PlatformIO installs the pinned platform on the first build).
# Usage: new_app.sh <board-id> <app-name> [<workspace-dir>] [template] [--no-open]
#   --no-open      stage 2d (open_ide.sh) without a VS Code window (headless runs)
#   workspace-dir  where apps live (default: $ESP_WS, "" = default)
#   template       a folder under templates/ (default uart-btn-led); see help.sh for the list
# Writes <workspace>/<app>/:
#   platformio.ini     pinned platform, board, framework arduino, -D<BOARD_DEFINE>,
#                      -Wall -Wextra for src/ only
#   src/               templates/_common/src (board/, func/ - the Arduino func layer shared with
#                      pio-arduino-rpipico2w) + the template's src (main.cpp: setup/loop)
#   tests/, arduino-app.env   test specs; record of what was used

. "$(dirname "$0")/env.sh"
OPEN=1; ARGS=()
for a in "$@"; do case "$a" in --no-open) OPEN=0;; --*) die "unknown option $a";; *) ARGS+=("$a");; esac; done
set -- "${ARGS[@]}"
[ $# -ge 2 ] || die "usage: new_app.sh <board-id> <app-name> [<workspace-dir>] [template] [--no-open]"
load_board "$1"; APP="$2"; WS="${3:-$ESP_WS}"; TPL="${4:-uart-btn-led}"
require_vars BOARD_DEFINE PIO_PLATFORM PIO_BOARD PIO_FRAMEWORK PIO_ENV
case "$APP" in *[!A-Za-z0-9_-]*|"") die "app name '$APP': use letters, digits, - and _";; esac
[ -d "$SKILL_DIR/templates/$TPL" ] && [ "${TPL#_}" = "$TPL" ] \
  || die "no template '$TPL' (have: $(ls "$SKILL_DIR/templates" | grep -v '^_' | tr '\n' ' '))"

mkdir -p "$WS" || die "cannot create $WS"; WS="$(cd "$WS" && pwd)"; APPDIR="$WS/$APP"
require_safe_path "$APPDIR" "app" 100
[ -e "$APPDIR" ] && die "$APPDIR already exists - pick another name (or delete it after asking the user)"
write_workspace_gitignore "$WS"
svc="$(path_synced "$WS")"; [ -n "$svc" ] && echo "WARN: $WS is in a $svc folder - pause sync if a build fails on locked files"

info "Creating $APPDIR (board $BOARD_ID, template $TPL)"
mkdir -p "$APPDIR"
# templates/_common (board + func layers) first, then the app template on top
for T in "$SKILL_DIR/templates/_common" "$SKILL_DIR/templates/$TPL"; do
  for part in src tests; do
    [ -d "$T/$part" ] && { mkdir -p "$APPDIR/$part"; cp -r "$T/$part/." "$APPDIR/$part/"; }
  done
done
[ -f "$APPDIR/src/main.cpp" ] || die "template $TPL has no src/main.cpp"

cat >"$APPDIR/platformio.ini" <<EOF
; Generated by pio-arduino-esp32s3box/new_app.sh $(date '+%Y-%m-%d %H:%M') - board $BOARD_ID, template $TPL.
; The platform is pinned to an exact version (it pins arduino-esp32 and the toolchain): change it
; only together with the board profile (boards/$BOARD_ID/pio-arduino-esp32s3box/board.env).
[env:$PIO_ENV]
platform = $PIO_PLATFORM
board = $PIO_BOARD
framework = $PIO_FRAMEWORK
build_flags = -D$BOARD_DEFINE
; warnings for our own code only (src/), not for the framework
build_src_flags = -Wall -Wextra
monitor_speed = ${CONSOLE_BAUD:-115200}
EOF

cat >"$APPDIR/arduino-app.env" <<EOF
# written by pio-arduino-esp32s3box/new_app.sh $(date '+%Y-%m-%d %H:%M')
APP_BOARD=$BOARD_ID
APP_BOARD_DEFINE=$BOARD_DEFINE
APP_TEMPLATE=$TPL
APP_PIO_ENV=$PIO_ENV
APP_PIO_PLATFORM=$PIO_PLATFORM
APP_PIO_BOARD=$PIO_BOARD
APP_IDF_TARGET=${IDF_TARGET:-esp32s3}
EOF
info "Created $APPDIR  (board $BOARD_ID, template $TPL)"
info "Next: build.sh $APPDIR"
fw_new_app_ide "$APPDIR" $OPEN     # stage 2d: hand over to VS Code + PlatformIO IDE
